/**
 *    Store: SOrg
 *    Description: all org data
 *
 *
 *  **THIS CODE WAS GENERATED BY A TOOL**
 * **eOcean vue nuxt generator
 *
 * This is an implementation of a simple generic store to provide
 * -CRUD
 * -get all
 * -search
 *
 * for a single dto (Schema1 in this case).
 * A test data json file is used to spoof a database for now but this would be
 * easily replaced by a mongo api/db.
 */

import displayDef from "@/store/display-schemas/SOrg.json";

export const state = () => ({
  schemaDisplayDefinition: displayDef,
  all: [{"orgName":"BkTek"},{"orgName":"TRex"}], //All orgs we are tracking

});

export const getters = {
  schemaDisplayDefinition: (state) => state.schemaDisplayDefinition,
  all: (state) => state.all, //All orgs we are tracking

};

export const actions = {
  update(ctx, data) {
    //FInd data in all by id then update.
    const hits = ctx.state.all.filter((f) => f.id == data.id);
    if (!hits)
      throw `Error: found 0 hits in all data collection for id (${data.id})`;
    if (hits.length > 1)
      throw `Error: found multiple id's in all data collection for id (${data.id})`;

    //Update data in all data for hit and fire mutation
    ctx.commit("update", { dataToUpdate: hits[0], newData: data });
  },
  
};

export const mutations = {
  schemaDisplayDefinition: (state, value) =>
    (state.schemaDisplayDefinition = value),
  update(state, data) {
    data.dataToUpdate[data.newData.fieldDef.fieldName] = data.newData.newValue;
  },
  add(state, text) {
    all.list.push({
      text,
      done: false,
    });
  },
  remove(state, { todo }) {
    all.list.splice(state.list.indexOf(todo), 1);
  },
  all: (state, value) => state.all=value, //All orgs we are tracking

};
