/**
 *    Store: SAuth
 *    Description: Manages user auth and logged in state.
 *
 *
 *  **THIS CODE WAS GENERATED BY A TOOL**
 * **eOcean vue nuxt generator
 *
 * This is an implementation of a store to implement login
 * functionality
 * -auth management
 * -login state management
 * -etc.
 */

export const state = () => ({
  showDevControls: false,
})

export const getters = {
  showDevControls: (state) => state.showDevControls,
}

export const actions = {
  showDevControls: (ctx, value) => {
    ctx.commit('showDevControls', value)
  },
}

export const mutations = {
  showDevControls: (state, value) => (state.showDevControls = value),
}
