
<!--This control generated by eox:pneuma scaffolding engine
  Control Name: 
  Control Description: 
-->

<!--This control generated by eox:pneuma scaffolding engine
  Control Name: 
  Control Description: 
  Usage: 
  -tag: <c-login></c-login>
  -props: set homeRoute to the route you want to goto after successful login.
-->
<template>
  <div>
    <!-- {{ $data }} -->
    <!-- {{ isLoggedIn }}
    Store {{ $store.getters["SAuth/isLoggedIn"] }} -->

    <v-btn class="elevation-0" v-if="!isLoggedIn" @click="show = true"
      >Login</v-btn
    >

    <c-profile-card v-if="me && isLoggedIn"></c-profile-card>

    <v-dialog v-model="show" max-width="450px">
      <v-card class="elevation-8" :loading="loading">
        <v-toolbar dense flat>
          <v-icon>mdi-fingerprint</v-icon>

          <v-spacer></v-spacer>
          <!-- <span class="overline">Login</span> -->
        </v-toolbar>
        <v-card-text>
          <v-form v-model="isValid">
            <v-text-field
              label="Login"
              name="login"
              prepend-icon="mdi-account"
              type="text"
              v-model="un"
              :rules="[rules.required]"
            ></v-text-field>

            <v-text-field
              id="password"
              label="Password"
              name="password"
              prepend-icon="mdi-lock"
              type="password"
              v-model="pw"
              @keypress="pwKeypress"
              :rules="[rules.required]"
            ></v-text-field>
          </v-form>
        </v-card-text>
        <v-card-text>
          <span
            v-if="loginErrMessage"
            class="error--text d-flex justify-center"
            >{{ loginErrMessage }}</span
          >
        </v-card-text>
        <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn color="primary" text @click="show = false">Cancel</v-btn>
          <v-btn color="primary" text @click="doLogin" :disabled="!isValid"
            >Login</v-btn
          >
        </v-card-actions>
      </v-card>
    </v-dialog>
  </div>
</template>

<script>
import { mapGetters } from "vuex";

export default {
  computed: {
    ...mapGetters({isLoggedIn: 'SAuth/isLoggedIn',loading: 'SAuth/loading',loginErrMessage: 'SAuth/loginErrMessage',me: 'SAuth/me',}),
  },

  data() {
    return {
      show: false,
      un: "",
      pw: "",
      rules: {
        required: (value) => !!value || "Required.",
      },
      isValid: true,
    };
  },
  watch: {
    isLoggedIn(newValue, oldValue) {
      if (newValue) {
        this.show = false;
      }
    },
    show(newValue) {
      this.$emit("input", newValue);
    },
  },
  props: {
    value: Boolean,
    homeRoute: {
      default: "/",
    },
  },
  methods: {
    doLogin: async function () {
      await this.$store.dispatch("SAuth/doLogin", {
        userName: this.un,
        password: this.pw,
      });

      if (this.isLoggedIn) {
        this.$router.push({ path: this.homeRoute });
      }
    },

    pwKeypress(e) {
      if (e.key === "Enter" && this.isValid) {
        this.doLogin();
      }
    },
  },
};
</script>

<style>
</style>