<!--This page generated by eox:pneuma scaffolding engine
  Page Name: PMeetingSeries
  Page Description: Shows a navigable view of meetings in a meeting series
-->
<template>
  <v-container>
    <v-row v-if="$store.getters['SSys/showDevControls']">
      <v-col> Data: {{ $data }} </v-col>
      <v-col> All: {{ all }} </v-col>
      <v-col> Headers: {{ headers }} </v-col>
    </v-row>
    <v-row justify="center" align="center" no-gutters>
      <v-col cols="12">
        <div>
          <v-alert dense type="info">
            This is a Nuxt Page called <strong>PMeetingSeries</strong> - it was
            generated by <strong>pneuma</strong>, a scaffolding CLI by
            <strong>eOcean Data</strong>
          </v-alert>
        </div>
      </v-col>
    </v-row>

    <v-row>
      <v-col>
        <ArrayEditor
          :all="all"
          :schemaDisplayDefinition="schemaDisplayDefinition"
        ></ArrayEditor>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
import { mapGetters } from 'vuex'

import Logo from '~/components/Logo.vue'
import VuetifyLogo from '~/components/VuetifyLogo.vue'

const TOKENIZED = {
  PAGE_NAME: 'PMeetingSeries',
}

export default {
  components: {
    Logo,
    VuetifyLogo,
  },
  computed: {
    computeSelectedSubtree(selectedItem, fieldName) {
      return (selectedItem, fieldName) => {
        return [{ id: selectedItem.id, fieldName }]
      }
    },
    schemaDisplayDefinition() {
      return this.$store.getters['SMeetingSeries/schemaDisplayDefinition']
    },
    headers() {
      if (!this.schemaDisplayDefinition) {
        return []
      }

      return this.schemaDisplayDefinition.map((col) => {
        return {
          text: col.fieldName,
          value: col.fieldName,
        }
      })
    },

    ...mapGetters({ all: 'SMeetingSeries/all' }),
  },
  props: {
    light: {
      type: Boolean,
      default: false,
    },
  },
  methods: {
    computeParentFieldName(selectedItem, item) {
      return (
        (selectedItem ? selectedItem.id : '') +
        '/' +
        (item ? item.fieldName : null)
      )
    },
    formatArrayCellDescription(selectedItem, item) {
      if (!selectedItem) return ''
      if (!item) return ''

      return selectedItem[item.fieldName]
    },

    computeArrayId(item, selectedItem) {
      return (selectedItem ? selectedItem.id : 'noId') + item.fieldName
    },
    formatCell(value) {
      console.log(value)
      if (Array.isArray(value)) {
        return `Array: length(${value.length})`
      }

      return value
    },
    updateItem(fieldDef, id, e) {
      this.$store.dispatch('SMeetingSeries/update', {
        fieldDef,
        id: id,
        newValue: e,
      })
    },
    rowClick: function (item, row) {
      row.select(true)
      this.selectedId = item.id
      this.selectedItem = item
    },
  },

  data() {
    return {
      search: null,
      arrayEditToggle: {},
      pageName: TOKENIZED.PAGE_NAME,
      selectedItem: null,
      selectedId: null,
    }
  },
}
</script>


<style lang="scss">
tr.v-data-table__selected {
  background: $selected-row-color !important; /**Simply run npm install --save-dev node-sass sass-loader then set your vars in /assets/variables.scss (from https://medium.com/@wearethreebears/globally-accessible-css-and-scss-sass-in-your-nuxt-component-files-7c1c012d31bd) */
}
</style>