<!--This page generated by eox:pneuma scaffolding engine
  Page Name: PMeetingSeries
  Page Description: Shows a navigable view of meetings in a meeting series
-->
<template>
  <v-container>
    <v-row>
      <v-col> Data: {{ $data }} </v-col>
      <v-col> All: {{ all }} </v-col>
      <v-col> Headers: {{ headers }} </v-col>
    </v-row>
    <v-row justify="center" align="center">
      <v-col cols="12" sm="8" md="6">
        <div class="text-center">
          <logo />
          <vuetify-logo />
        </div>
        <v-card>
          <v-card-title class="headline">
            Welcome to the Vuetify + Nuxt.js template
          </v-card-title>
          <v-card-text class="text-h3 blue--text text--lighten-1">
            <p>
              This is a Nuxt Page called PMeetingSeries - it was generated by
              pneuma, a scaffolding CLI by eOcean Data
            </p>
          </v-card-text>

          <v-card-text class="text-h3 blue--text text--lighten-1">
            <v-row>
              <v-col>
                <p>What does PMeetingSeries do?</p>
              </v-col>
              <v-col>
                Shows a navigable view of meetings in a meeting series
              </v-col>
            </v-row>
          </v-card-text>
          <v-card-actions>
            <v-spacer />
            <v-btn color="primary" nuxt to="/inspire"> Continue </v-btn>
          </v-card-actions>
        </v-card>
      </v-col>
    </v-row>

    <v-row>
      <v-col>
        <v-card :light="light ? light : dark">
          Schema 1 CRUD

          {{ $data }}
          Selected id : {{ selectedId }}
          <div class="masterList">
            <v-container>
              <v-row>
                <v-col>
                  <v-data-table
                    dense
                    :headers="headers"
                    :items="all"
                    class="elevation-1"
                    @click:row="rowClick"
                    item-key="id"
                    single-select
                  >
                    <template v-slot:top>
                      <v-text-field
                        class="mx-4"
                        prepend-icon="mdi-magnify"
                        label="Search table"
                        v-model="search"
                      ></v-text-field>
                    </template>

                    <!-- This template looks for headers with formatters and executes them -->
                    <template
                      v-for="header in headers"
                      v-slot:[`item.${header.value}`]="{ header, value }"
                    >
                      {{ formatCell(value) }}
                    </template>
                  </v-data-table>
                </v-col>
              </v-row>
            </v-container>
          </div>

          <div class="selectedItem">
            <v-container>
              <v-row
                v-for="item in schemaDisplayDefinition"
                :key="item.fieldName"
              >
                <v-col>
                  <v-row>
                    <v-col> {{ item.fieldName }} </v-col>
                    <v-col
                      v-if="
                        selectedItem &&
                        !Array.isArray(selectedItem[item.fieldName])
                      "
                    >
                      <v-text-field
                        v-if="selectedItem"
                        :value="selectedItem[item.fieldName]"
                        @input="updateItem(item, selectedItem.id, $event)"
                        label="Regular"
                        clearable
                      ></v-text-field>
                    </v-col>
                    <v-col v-else>
                      <v-row>
                        <v-col>
                          {{ formatArrayCellDescription(selectedItem, item) }}
                        </v-col>
                        <v-col cols="2">
                          <v-switch
                            v-model="
                              arrayEditToggle[
                                computeArrayId(item, selectedItem)
                              ]
                            "
                            >Edit</v-switch
                          >
                        </v-col>
                      </v-row>
                    </v-col>
                  </v-row>

                  <v-expand-transition>
                    <v-row
                      v-if="
                        selectedItem &&
                        Array.isArray(selectedItem[item.fieldName]) &&
                        arrayEditToggle[computeArrayId(item, selectedItem)]
                      "
                    >
                      <v-col class="tile blue ma-2 rounded elevation-12">
                        <ArrayEditor
                          :all="
                            selectedItem ? selectedItem[item.fieldName] : null
                          "
                          v-if="selectedItem"
                          :value="selectedItem[item.fieldName]"
                          :parentFieldName="
                            computeParentFieldName(selectedItem, item)
                          "
                          :schemaDisplayDefinition="item.childDisplaySchema"
                          :allSubtreeAddress="
                            computeSelectedSubtree(selectedItem, item.fieldName)
                          "
                        ></ArrayEditor>
                      </v-col>
                    </v-row>
                  </v-expand-transition>
                  <!--<v-row>
                    <v-col>{{ item.fieldName }}</v-col>
                   <v-col
                      v-if="
                        selectedItem &&
                        !Array.isArray(selectedItem[item.fieldName])
                      "
                    >
                      <v-text-field
                        v-if="selectedItem"
                        :value="selectedItem[item.fieldName]"
                        @input="updateItem(item, selectedItem.id, $event)"
                        label="Regular"
                        clearable
                      ></v-text-field
                    ></v-col>
                  </v-row>
                  <v-row v-if="Array.isArray(selectedItem[item.fieldName])">
                    <v-col>
                      <ArrayEditor
                        v-if="selectedItem"
                        :value="selectedItem[item.fieldName]"
                      ></ArrayEditor
                    ></v-col>
                  </v-row> -->
                </v-col>
              </v-row>
            </v-container>
          </div>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
import { mapGetters } from 'vuex'

import Logo from '~/components/Logo.vue'
import VuetifyLogo from '~/components/VuetifyLogo.vue'

const TOKENIZED = {
  PAGE_NAME: 'PMeetingSeries',
}

export default {
  components: {
    Logo,
    VuetifyLogo,
  },
  computed: {
    computeSelectedSubtree(selectedItem, fieldName) {
      return (selectedItem, fieldName) => {
        return [{ id: selectedItem.id, fieldName }]
      }
    },
    schemaDisplayDefinition() {
      return this.$store.getters['SMeetingSeries/schemaDisplayDefinition']
    },
    headers() {
      if (!this.schemaDisplayDefinition) {
        return []
      }

      return this.schemaDisplayDefinition.map((col) => {
        return {
          text: col.fieldName,
          value: col.fieldName,
        }
      })
    },

    ...mapGetters({ all: 'SMeetingSeries/all' }),
  },
  props: {
    light: {
      type: Boolean,
      default: false,
    },
  },
  methods: {
    computeParentFieldName(selectedItem, item) {
      return (
        (selectedItem ? selectedItem.id : '') +
        '/' +
        (item ? item.fieldName : null)
      )
    },
    formatArrayCellDescription(selectedItem, item) {
      if (!selectedItem) return ''
      if (!item) return ''

      return selectedItem[item.fieldName]
    },

    computeArrayId(item, selectedItem) {
      return (selectedItem ? selectedItem.id : 'noId') + item.fieldName
    },
    formatCell(value) {
      console.log(value)
      if (Array.isArray(value)) {
        return `Array: length(${value.length})`
      }

      return value
    },
    updateItem(fieldDef, id, e) {
      this.$store.dispatch('SMeetingSeries/update', {
        fieldDef,
        id: id,
        newValue: e,
      })
    },
    rowClick: function (item, row) {
      row.select(true)
      this.selectedId = item.id
      this.selectedItem = item
    },
  },

  data() {
    return {
      search: null,
      arrayEditToggle: {},
      pageName: TOKENIZED.PAGE_NAME,
      selectedItem: null,
      selectedId: null,
    }
  },
}
</script>


<style lang="scss">
tr.v-data-table__selected {
  background: $selected-row-color !important; /**Simply run npm install --save-dev node-sass sass-loader then set your vars in /assets/variables.scss (from https://medium.com/@wearethreebears/globally-accessible-css-and-scss-sass-in-your-nuxt-component-files-7c1c012d31bd) */
}
</style>